Feat str replace
maxinteger/pocket-lisp-stdlib pull request #41
Opened 2021-09-25 02:36 UTC by vektor8891

2021-09-25 02:37 UTC, vektor8891 commented
@maxinteger I've created a new branch with the two requested functions. Can you pls take a look?

2021-09-30 08:39 UTC, maxinteger requested changes
Looks very good. I just need one tiny change.

2021-09-30 08:39 UTC, maxinteger commented on src/data/string/stringFn.ts
> +export const replaceRegexp = (regexp: PLString, flags: PLString, to: PLString, str: PLString): PLString => {
could you please change order of parameters to:
```suggestion
export const replaceRegexp = (flags: PLString, regexp: PLString, to: PLString, str: PLString): PLString => {
```
this way you can define replace function with default flags:
```ts
(let replace-global (replace-regexp "g"))
```

2021-09-30 12:25 UTC, vektor8891 commented
@maxinteger Done. Can you pls take a look?

2021-10-02 22:01 UTC, merged

2021-10-20 21:31 UTC, vektor8891 commented
@maxinteger Can you pls deploy the newest version? I still cannot use this function on the website.